### ISSUE TITLE
Enable flags such as --strict to be specified in gjslintrc

### ISSUE THREAD

**Issue by KenRud** [mrmeku/brackets-closure-linter#2]
I would like to specify in the gjslintrc config file whether to use strict linting. I saw that there are already a couple of TODOs to have this feature completed. I will consider implementing this when I have some spare time if no one else wants to jump on it.

**Comment by mrmeku** [comment]
By all means! As long as we are implementing toggling of the strict flag we should also probably tackle the --nojsdoc flag as well. As far as the .gjslintrc syntax goes how does this sound?

{
   flags: {
     gjslint: '--strict --nojsdoc --otherflags',
     fixjsstyle: '--strict --nojsdoc --otherflags'
  }
}

**Comment by KenRud** [comment]
That would be great and covers all other possible flags that people could
configure.

**Comment by mrmeku** [comment]
The deed is done. Let me know if you have any questions about it!
